"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/AsciiObject/AsciiObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/AsciiObject/AsciiObjectVanilla";
import * as WebGPU from "@/lib/AsciiObject/AsciiObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type AsciiObjectInstance = WebGL.AsciiObjectInstance;
type AsciiObjectOptions = WebGL.AsciiObjectOptions;

export interface AsciiObjectProps extends AsciiObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function AsciiObject({
  className,
  style,
  ...options
}: AsciiObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createAsciiObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<AsciiObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createAsciiObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createAsciiObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { AsciiObjectInstance, AsciiObjectOptions };

export default AsciiObject;
