"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/Displacement/Displacement.tsx. Do not edit.

import {
  useEffect,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from "react";

import * as WebGL from "@/lib/Displacement/DisplacementVanilla";
import * as WebGPU from "@/lib/Displacement/DisplacementWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type DisplacementInstance = WebGL.DisplacementInstance;
type DisplacementOptions = WebGL.DisplacementOptions;

export interface DisplacementProps extends DisplacementOptions {
  children: ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

const emptySubscribe = () => () => {};

export function Displacement({
  children,
  className,
  style,
  ...options
}: DisplacementProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createDisplacement, supportsHtmlInCanvas } = engine;

  const sourceRef = useRef<HTMLCanvasElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const outputRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<DisplacementInstance | null>(null);
  const [initialOptions] = useState(options);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    // Retry native initialization when switching renderer engines.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setFailed(false);
  }, [renderer]);

  const supported = useSyncExternalStore(
    emptySubscribe,
    supportsHtmlInCanvas,
    () => false,
  );
  const native = supported && !failed;

  useEffect(() => {
    const source = sourceRef.current;
    const content = contentRef.current;
    const output = outputRef.current;
    if (!source || !content || !output) return;
    instanceRef.current = createDisplacement(
      { source, content, output },
      initialOptions,
    );
    if (native && !instanceRef.current) setFailed(true);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, native, renderer, createDisplacement]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={sourceRef}
        // @ts-expect-error experimental html-in-canvas attribute
        layoutsubtree="true"
        suppressHydrationWarning
        style={
          native
            ? { position: "absolute", inset: 0, width: "100%", height: "100%" }
            : { display: "none" }
        }
      >
        {native ? (
          <div
            ref={contentRef}
            style={{
              position: "relative",
              width: "100%",
              height: "100%",
              overflow: "auto",
            }}
          >
            {children}
          </div>
        ) : null}
      </canvas>
      {!native ? (
        <div
          ref={contentRef}
          style={{
            position: "relative",
            width: "100%",
            height: "100%",
            overflow: "auto",
          }}
        >
          {children}
        </div>
      ) : null}
      <canvas
        ref={outputRef}
        aria-hidden
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          pointerEvents: "none",
        }}
      />
    </div>
  );
}

export type { DisplacementInstance, DisplacementOptions };

export default Displacement;
