"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/DitheredObject/DitheredObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/DitheredObject/DitheredObjectVanilla";
import * as WebGPU from "@/lib/DitheredObject/DitheredObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type DitheredObjectInstance = WebGL.DitheredObjectInstance;
type DitheredObjectOptions = WebGL.DitheredObjectOptions;

export interface DitheredObjectProps extends DitheredObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function DitheredObject({
  className,
  style,
  ...options
}: DitheredObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createDitheredObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<DitheredObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createDitheredObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createDitheredObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { DitheredObjectInstance, DitheredObjectOptions };

export default DitheredObject;
