"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/GlassObject/GlassObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/GlassObject/GlassObjectVanilla";
import * as WebGPU from "@/lib/GlassObject/GlassObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type GlassObjectInstance = WebGL.GlassObjectInstance;
type GlassObjectOptions = WebGL.GlassObjectOptions;

export interface GlassObjectProps extends GlassObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function GlassObject({
  className,
  style,
  ...options
}: GlassObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createGlassObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<GlassObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createGlassObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createGlassObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { GlassObjectInstance, GlassObjectOptions };

export default GlassObject;
