"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/InkObject/InkObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/InkObject/InkObjectVanilla";
import * as WebGPU from "@/lib/InkObject/InkObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type InkObjectInstance = WebGL.InkObjectInstance;
type InkObjectOptions = WebGL.InkObjectOptions;

export interface InkObjectProps extends InkObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function InkObject({
  className,
  style,
  ...options
}: InkObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createInkObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<InkObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createInkObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createInkObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { InkObjectInstance, InkObjectOptions };

export default InkObject;
