"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/LiquidObject/LiquidObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/LiquidObject/LiquidObjectVanilla";
import * as WebGPU from "@/lib/LiquidObject/LiquidObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type LiquidObjectInstance = WebGL.LiquidObjectInstance;
type LiquidObjectOptions = WebGL.LiquidObjectOptions;

export interface LiquidObjectProps extends LiquidObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function LiquidObject({
  className,
  style,
  ...options
}: LiquidObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createLiquidObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<LiquidObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createLiquidObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createLiquidObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { LiquidObjectInstance, LiquidObjectOptions };

export default LiquidObject;
