"use client";
// Generated by scripts/build-live-wrappers.mts from src/lib/ParticleObject/ParticleObject.tsx. Do not edit.

import { useEffect, useRef, useState } from "react";

import * as WebGL from "@/lib/ParticleObject/ParticleObjectVanilla";
import * as WebGPU from "@/lib/ParticleObject/ParticleObjectWebGPU";
import { useLiveRenderer } from "@/components/docs/live-renderer";

type ParticleObjectInstance = WebGL.ParticleObjectInstance;
type ParticleObjectOptions = WebGL.ParticleObjectOptions;

export interface ParticleObjectProps extends ParticleObjectOptions {
  className?: string;
  style?: React.CSSProperties;
}

export function ParticleObject({
  className,
  style,
  ...options
}: ParticleObjectProps) {
  const renderer = useLiveRenderer();
  const engine = renderer === "webgpu" ? WebGPU : WebGL;
  const { createParticleObject } = engine;

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<ParticleObjectInstance | null>(null);
  const [initialOptions] = useState(options);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    instanceRef.current = createParticleObject({ canvas }, initialOptions);
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [initialOptions, renderer, createParticleObject]);

  useEffect(() => {
    instanceRef.current?.setOptions(options);
  });

  return (
    <div key={renderer} className={className} style={{ position: "relative", ...style }}>
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          display: "block",
          touchAction: "none",
        }}
      />
    </div>
  );
}

export type { ParticleObjectInstance, ParticleObjectOptions };

export default ParticleObject;
